name: CI
on: push

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Install Foreman
        uses: Roblox/setup-foreman@v1
        with:
          version: "^1.0.0"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Foreman
        run: foreman install

      - name: Download Packages
        run: wally install

      - name: Run Selene
        run: |
          selene generate-roblox-std
          selene src
